// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASeNAN_gAAprz5oEwuDAVPkK8eF6FEdOo',
    appId: '1:794853147970:web:4aa8dceff01af8ed2774db',
    messagingSenderId: '794853147970',
    projectId: 'gerenciador_de_tarefas-388217',
    authDomain: 'gerenciador_de_tarefas-388217.firebaseapp.com',
    storageBucket: 'gerenciador_de_tarefas-388217.appspot.com',
    measurementId: 'G-B827CLFZ4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgI_qTvvcGe_mG_X_Xcr5JCI6SaSKq9-Y',
    appId: '1:794853147970:android:efa05d631d9d9b5a2774db',
    messagingSenderId: '794853147970',
    projectId: 'gerenciador_de_tarefas-388217',
    storageBucket: 'gerenciador_de_tarefas-388217.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_RwXw_EuV8sKfdu8eo1J-boyDazVwiEM',
    appId: '1:794853147970:ios:a87efcaed2762db62774db',
    messagingSenderId: '794853147970',
    projectId: 'gerenciador_de_tarefas-388217',
    storageBucket: 'gerenciador_de_tarefas-388217.appspot.com',
    iosClientId: '794853147970-d2g74fk038gmt7tnl0mjogclkjji77m2.apps.googleusercontent.com',
    iosBundleId: 'br.alvaro.neto.gerenciadorDeTarefas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_RwXw_EuV8sKfdu8eo1J-boyDazVwiEM',
    appId: '1:794853147970:ios:9d030137de1c80d62774db',
    messagingSenderId: '794853147970',
    projectId: 'gerenciador_de_tarefas-388217',
    storageBucket: 'gerenciador_de_tarefas-388217.appspot.com',
    iosClientId: '794853147970-41cb685jurrbl36d8s7gcfuu4n1neh5b.apps.googleusercontent.com',
    iosBundleId: 'br.alvaro.neto.gerenciador_de_tarefas',
  );
}
